# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c8a11adef6b3571cf5ee4f08e5a4b57bf91837fbf05533b3a8dd5449d9101b5b7cbae85f5ef1170687eda32950381d59e65aa148d05d710b8d799dd8f775d2

test:
  secret_key_base: 1f0a3174dd437edc02598928ce02850ff3e0179e9e975622d892c1aa668a3efc4f8cb180c035e2830d2b7f814e90456d19a697d886419fad943229d87cfe9430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
